### PR TITLE
Pull Request 9

### PR DESCRIPTION
**Pull request by PatGarza20**
In the midst of struggling a lot to figure out how to test logins for the sake of doing something that matches my project proposal, I wrote some simpler unit tests for HostAddress.

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @michaelmunje

**Comment by kyledewey** [comment]
Also assigned @mj-shi

**Comment by kyledewey** [comment]
Also assigned @DavidWants2Learn

**Review by michaelmunje — APPROVED** [review]
Looks good.

**Review by mj-shi — APPROVED** [review]
Tests look good, explained well. Indentation and spacing is well done.

**Pull request merged**
