### PR TITLE
Pull Request #3 - First Unit Testing

### PR DESCRIPTION
**Pull request by PatGarza20**
Added GitRemoteTests.cs to perform unit testing on GitRemote.cs. Wrote two simple unit tests checking the functionality of GitRemote's values/pointers and wrote AssertEqual/AssertNotEqual functions in AssertExtensions.cs so that assertions can be used in current and future testing of GitRemote.

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @DavidWants2Learn

**Comment by kyledewey** [comment]
Additionally assigned @mj-shi

**Comment by DavidWants2Learn** [comment]
I'm having trouble pushing into the git repo.

I'm currently still reading / researching the react library. Learning how
to code client side via Node.js,
and also learning how I can implement Jest and enzyme for Node.js testing.

**Review by mj-shi — APPROVED** [review]
Code is well written; organized, variable and parameter names are meaningful, indentation and spacing is readable. Although the test method names are pretty self-explanatory, you could add a comment line before each test explaining what's being tested. Nice job!

**Pull request merged**
