### PR TITLE
Pull Request 1

### PR DESCRIPTION
**Pull request by PatGarza20**
Text document describing my progress with understanding the codebase so far.

### CODE REVIEW

**Comment by kyledewey** [comment]
Review requested from @LuisAbularach

**Comment by kyledewey** [comment]
Additional review requested from @mj-shi

**Review by LuisAbularach — APPROVED** [review]
Seems like a good description of where you are with regards to Unity and where you can maybe start testing.

**Review by mj-shi — APPROVED** [review]
Documentation provides good background information and description of the user 's experience and system

**Pull request merged**
